### PR TITLE
60: Jackson deserialization for Quantity

### LINKED ISSUE #60: Jackson deserialization for `Quantity` interface does not exist
I have recently discovered and started to use all the [Units of Measurement library echosystem](http://unitsofmeasurement.github.io/).
Now I wanted to serialize/deserialize some `Quantity`'s instances, but I have realised that is not possible to deserialize them.

The following JUnit 5 (with pojo class included)

```
class ChargeDeserializationTest
{

    static final ObjectMapper mapper = new ObjectMapper();
    static
    {
        mapper.registerModule(new UnitJacksonModule())
            .registerModules(new JavaTimeModule());
    }

    @Test
    public void roundtrip() throws Exception
    {
        Charge charge = new Charge();
        charge.setWhen(Instant.ofEpochMilli(nextLong()));
        charge.setRunAlong(Quantities.getQuantity(nextLong(), Units.METRE));
        charge.setWith(Quantities.getQuantity(nextLong(), Units.CUBIC_METRE));

        String serialization = mapper.writeValueAsString(charge);
        Charge deserialization = mapper.readValue(serialization, Charge.class);
    }

    static class Charge
    {

        private Instant when;
        private Quantity<Length> runAlong;
        private Quantity<Volume> with;

        public Instant getWhen()
        {
            return when;
        }

        public void setWhen(final Instant when)
        {
            this.when = when;
        }

        public Quantity<Length> getRunAlong()
        {
            return runAlong;
        }

        public void setRunAlong(final Quantity<Length> runAlong)
        {
            this.runAlong = runAlong;
        }

        public Quantity<Volume> getWith()
        {
            return with;
        }

        public void setWith(final Quantity<Volume> with)
        {
            this.with = with;
        }

    }

}
```

throws the exception,

```
Cannot construct instance of `javax.measure.Quantity` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (String)"{"when":4484040231309519.872000000,"runAlong":{"unit":"m","scale":"ABSOLUTE","value":3535414706998429696},"with":{"unit":"m3","scale":"ABSOLUTE","value":6316882200111963136}}"; line: 1, column: 47] (through reference chain: com.github.lucasvc.uom.lib.jackson.quantity.deserialize.ChargeDeserializationTest$Charge["runAlong"])
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `javax.measure.Quantity` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (String)"{"when":4484040231309519.872000000,"runAlong":{"unit":"m","scale":"ABSOLUTE","value":3535414706998429696},"with":{"unit":"m3","scale":"ABSOLUTE","value":6316882200111963136}}"; line: 1, column: 47] (through reference chain: com.github.lucasvc.uom.lib.jackson.quantity.deserialize.ChargeDeserializationTest$Charge["runAlong"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1589)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1055)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:265)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173)
	at com.github.lucasvc.uom.lib.jackson.quantity.deserialize.ChargeDeserializationTest.roundtrip(ChargeDeserializationTest.java:40)
	....
	at java.lang.Thread.run(Thread.java:748)
```

* Is this expected?
* Am I using correctly the library?

### PR DESCRIPTION
**Pull request by bantu**
Fix #60 

As requested here: https://github.com/unitsofmeasurement/uom-lib/issues/60#issuecomment-938682634

---
This change is [Reviewable](https://reviewable.io/reviews/unitsofmeasurement/uom-lib/72)

### CODE REVIEW

**Comment by bantu** [comment]
Reimplemented and simplified. Commits should probably be squashed.

**Comment by keilw** [comment]
Unfortunately it breaks the build ;-/

**Comment by lucasvc** [comment]
@GregJohnStewart I know, as I said
> even Jackson by default use the class member name/method name

But then you leave to Jackson that task, which could change in the future.

**Comment by bantu** [comment]
> Unfortunately it breaks the build ;-/

Hmm. Why only after merge?

**Comment by bantu** [comment]
@keilw It looks like this change has not shipped yet. Are there any plans on shipping it any time soon?

**Comment by fref** [comment]
+1 on having a release with this change

**Comment by keilw** [comment]
We plan an MR2 of JSR 385 in the course of this quater, so there will be new releases of uom-lib-common (before the RI) and the other libraries (after MR2 of API and RI) soon anyway.

**Comment by fref** [comment]
How could we be of some help?

**Pull request merged**
